# Generated by Django 4.2.7 on 2025-12-12 03:38

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import produccion.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('supervisor', 'Supervisor'), ('control_calidad', 'Control de Calidad')], help_text='Rol del usuario en el sistema', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del usuario')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(help_text='Código identificador del colaborador', unique=True)),
                ('nombre', models.CharField(help_text='Nombre del colaborador', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del colaborador', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el colaborador está activo en el sistema')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que fue cargado al sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'colaboradores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HojaProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de inicio de la hoja de procesos')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización de la hoja de procesos', null=True)),
                ('finalizada', models.BooleanField(default=False, help_text='Indica si la hoja de procesos está finalizada')),
            ],
            options={
                'verbose_name': 'Hoja de Procesos',
                'verbose_name_plural': 'Hojas de Procesos',
                'db_table': 'hojas_procesos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la línea de producción', max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la línea está operativa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la línea', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Línea de Producción',
                'verbose_name_plural': 'Líneas de Producción',
                'db_table': 'lineas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la máquina', max_length=100)),
                ('codigo', models.CharField(help_text='Código único de la máquina', max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la máquina está operativa')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'maquinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la materia prima. Ejemplo: LAC0001', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la materia prima. Ejemplo: manjar', max_length=200)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('unidades', 'Unidades')], default='kg', help_text='Unidad de medida por defecto de esta materia prima', max_length=20)),
                ('requiere_lote', models.BooleanField(default=True, help_text='Indica si esta materia prima requiere registro de lote')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la materia prima está activa')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'db_table': 'materias_primas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(help_text='Código identificador del producto. Ejemplo: 410', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del producto. Ejemplo: alfajor manjar bitter', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está en producción')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=datetime.date.today, help_text='Fecha de la producción')),
                ('meta_produccion', models.PositiveIntegerField(help_text='Meta de producción en unidades', validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la tarea', max_length=500, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], db_index=True, default='pendiente', help_text='Estado actual de la tarea', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la tarea')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha y hora en que se inició la producción', null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se finalizó la producción', null=True)),
                ('linea', models.ForeignKey(help_text='Línea donde se realizará la producción', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='produccion.linea')),
                ('producto', models.ForeignKey(help_text='Producto a fabricar', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='produccion.producto')),
                ('supervisor_asignador', models.ForeignKey(help_text='Supervisor que creó esta tarea', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'ordering': ['-fecha', 'turno', 'linea'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de evento', max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Código del tipo de evento', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de evento', null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo de evento está activo')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'db_table': 'tipos_eventos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.PositiveIntegerField(help_text='Cantidad producida en unidades')),
                ('foto_etiquetas', models.ImageField(blank=True, help_text='Foto de las etiquetas utilizadas en la producción', null=True, upload_to='trazabilidad/etiquetas/%Y/%m/%d/', validators=[produccion.validators.validate_image_file], verbose_name='Foto de Etiquetas')),
                ('juliano', models.PositiveIntegerField(editable=False, help_text='Día juliano del año (1-366). Se calcula automáticamente desde fecha_creacion', verbose_name='Día Juliano')),
                ('lote', models.CharField(help_text='Lote de producción en formato: CÓDIGO_PRODUCTO-JULIANO-CÓDIGO_COLABORADOR. Ejemplo: 410-342-96', max_length=50, verbose_name='Lote')),
                ('estado', models.CharField(choices=[('en_revision', 'En Revisión'), ('liberado', 'Liberado'), ('retenido', 'Retenido')], default='en_revision', help_text='Estado de la trazabilidad', max_length=20)),
                ('motivo_retencion', models.TextField(blank=True, help_text="Motivo de retención (obligatorio si estado es 'retenido')", max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la trazabilidad')),
                ('hoja_procesos', models.OneToOneField(help_text='Hoja de procesos asociada', on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='produccion.hojaprocesos')),
            ],
            options={
                'verbose_name': 'Trazabilidad',
                'verbose_name_plural': 'Trazabilidades',
                'db_table': 'trazabilidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('AM', 'AM (06:15-13:35)'), ('Jornada', 'Jornada (08:00-17:30)'), ('PM', 'PM (13:25-22:05)')], help_text='Nombre del turno', max_length=20, unique=True)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el turno está activo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, help_text='Lote de la materia prima (puede ser null si no requiere lote)', max_length=100, null=True)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, help_text='Cantidad de materia prima usada', max_digits=10)),
                ('unidad_medida', models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('unidades', 'Unidades')], help_text='Unidad de medida de la cantidad', max_length=20)),
                ('materia_prima', models.ForeignKey(help_text='Materia prima utilizada', on_delete=django.db.models.deletion.PROTECT, related_name='trazabilidades', to='produccion.materiaprima')),
                ('trazabilidad', models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas_usadas', to='produccion.trazabilidad')),
            ],
            options={
                'verbose_name': 'Materia Prima Usada',
                'verbose_name_plural': 'Materias Primas Usadas',
                'db_table': 'trazabilidad_materias_primas',
                'ordering': ['materia_prima__codigo'],
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se registró este colaborador en la trazabilidad')),
                ('colaborador', models.ForeignKey(help_text='Colaborador que trabajó en la producción', on_delete=django.db.models.deletion.PROTECT, to='produccion.colaborador')),
                ('trazabilidad', models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_reales', to='produccion.trazabilidad')),
            ],
            options={
                'verbose_name': 'Colaborador en Trazabilidad',
                'verbose_name_plural': 'Colaboradores en Trazabilidad',
                'db_table': 'trazabilidad_colaborador',
                'ordering': ['fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='TareaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de asignación')),
                ('colaborador', models.ForeignKey(help_text='Colaborador asignado a la tarea', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to='produccion.colaborador')),
                ('tarea', models.ForeignKey(help_text='Tarea asignada', on_delete=django.db.models.deletion.CASCADE, related_name='tarea_colaboradores', to='produccion.tarea')),
            ],
            options={
                'verbose_name': 'Asignación de Colaborador',
                'verbose_name_plural': 'Asignaciones de Colaboradores',
                'db_table': 'tareas_colaboradores',
                'ordering': ['tarea', 'colaborador__codigo'],
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='turno',
            field=models.ForeignKey(help_text='Turno en que se realizará la producción', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='produccion.turno'),
        ),
        migrations.CreateModel(
            name='Reproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de de reproceso', max_digits=10)),
                ('causas', models.CharField(choices=[('temperatura_inadecuada', 'Temperatura Inadecuada'), ('tiempo_excedido', 'Tiempo de Proceso Excedido'), ('mezcla_incorrecta', 'Mezcla Incorrecta'), ('contaminacion', 'Contaminación'), ('error_operador', 'Error del Operador'), ('falla_maquina', 'Falla de Máquina'), ('materia_prima_defectuosa', 'Materia Prima Defectuosa'), ('otro', 'Otro (especificar)')], max_length=200, null=True)),
                ('trazabilidad_materia_prima', models.ForeignKey(help_text='Materia prima específica que tuvo reproceso', on_delete=django.db.models.deletion.CASCADE, related_name='reprocesos', to='produccion.trazabilidadmateriaprima')),
            ],
            options={
                'verbose_name': 'Reproceso',
                'verbose_name_plural': 'Reprocesos',
                'db_table': 'reprocesos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en la lista')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta materia prima está activa en la receta')),
                ('materia_prima', models.ForeignKey(help_text='Materia prima necesaria', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='produccion.materiaprima')),
                ('producto', models.ForeignKey(help_text='Producto al que pertenece esta materia prima', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
                'ordering': ['producto', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de merma', max_digits=10)),
                ('causas', models.CharField(choices=[('desperdicio_corte', 'Desperdicio en Corte'), ('producto_defectuoso', 'Producto Defectuoso'), ('derrame', 'Derrame o Pérdida'), ('caducidad', 'Producto Caducado'), ('error_pesaje', 'Error en Pesaje'), ('adherencia_equipo', 'Adherencia a Equipo'), ('rechazo_calidad', 'Rechazo de Calidad'), ('otro', 'Otro (especificar)')], max_length=200, null=True)),
                ('trazabilidad_materia_prima', models.ForeignKey(help_text='Materia prima específica que tuvo merma', on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='produccion.trazabilidadmateriaprima')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'db_table': 'mermas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='hojaprocesos',
            name='tarea',
            field=models.OneToOneField(help_text='Tarea asociada a esta hoja de procesos', on_delete=django.db.models.deletion.CASCADE, related_name='hoja_procesos', to='produccion.tarea'),
        ),
        migrations.CreateModel(
            name='FotoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Foto de las etiquetas', upload_to='etiquetas/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida de la foto')),
                ('trazabilidad', models.OneToOneField(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='foto_etiqueta', to='produccion.trazabilidad')),
            ],
            options={
                'verbose_name': 'Foto de Etiqueta',
                'verbose_name_plural': 'Fotos de Etiquetas',
                'db_table': 'fotos_etiquetas',
            },
        ),
        migrations.CreateModel(
            name='FirmaTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('supervisor', 'Supervisor'), ('control_calidad', 'Control de Calidad')], help_text='Tipo de firma', max_length=20)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la firma')),
                ('trazabilidad', models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='produccion.trazabilidad')),
                ('usuario', models.ForeignKey(help_text='Usuario que firmó', on_delete=django.db.models.deletion.PROTECT, related_name='firmas_trazabilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma de Trazabilidad',
                'verbose_name_plural': 'Firmas de Trazabilidad',
                'db_table': 'firmas_trazabilidad',
                'ordering': ['fecha_firma'],
            },
        ),
        migrations.CreateModel(
            name='EventoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(help_text='Hora de inicio del evento')),
                ('hora_fin', models.DateTimeField(blank=True, help_text='Hora de fin del evento', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre este evento', max_length=500, null=True)),
                ('hoja_procesos', models.ForeignKey(help_text='Hoja de procesos a la que pertenece este evento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='produccion.hojaprocesos')),
                ('tipo_evento', models.ForeignKey(help_text='Tipo de evento', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='produccion.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento de Proceso',
                'verbose_name_plural': 'Eventos de Procesos',
                'db_table': 'eventos_procesos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(help_text='Evento de proceso', on_delete=django.db.models.deletion.CASCADE, related_name='evento_maquinas', to='produccion.eventoproceso')),
                ('maquina', models.ForeignKey(help_text='Máquina utilizada', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='produccion.maquina')),
            ],
            options={
                'verbose_name': 'Máquina en Evento',
                'verbose_name_plural': 'Máquinas en Eventos',
                'db_table': 'eventos_maquinas',
            },
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['codigo'], name='colaborador_codigo_576cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['nombre', 'apellido'], name='colaborador_nombre_f9e921_idx'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='trazabilidadmateriaprima',
            unique_together={('trazabilidad', 'materia_prima')},
        ),
        migrations.AlterUniqueTogether(
            name='trazabilidadcolaborador',
            unique_together={('trazabilidad', 'colaborador')},
        ),
        migrations.AlterUniqueTogether(
            name='tareacolaborador',
            unique_together={('tarea', 'colaborador')},
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha', 'turno', 'linea'], name='tareas_fecha_bc5fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado'], name='tareas_estado_d4b02b_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha'], name='tareas_fecha_64a44e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together={('linea', 'turno', 'fecha', 'producto')},
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['producto'], name='recetas_product_c280de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receta',
            unique_together={('producto', 'materia_prima')},
        ),
        migrations.AlterUniqueTogether(
            name='firmatrazabilidad',
            unique_together={('trazabilidad', 'tipo_firma')},
        ),
        migrations.AlterUniqueTogether(
            name='eventomaquina',
            unique_together={('evento', 'maquina')},
        ),
    ]
