# Generated by Django 4.2.7 on 2025-10-06 01:54

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('supervisor', 'Supervisor'), ('control_calidad', 'Control de Calidad')], help_text='Rol del usuario en el sistema', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del usuario')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código identificador del colaborador', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del colaborador', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del colaborador', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el colaborador está activo en el sistema')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que fue cargado al sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'colaboradores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la línea de producción', max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la línea está operativa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la línea', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Línea de Producción',
                'verbose_name_plural': 'Líneas de Producción',
                'db_table': 'lineas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la materia prima. Ejemplo: LAC0001', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la materia prima. Ejemplo: manjar', max_length=200)),
                ('requiere_lote', models.BooleanField(default=True, help_text='Indica si esta materia prima requiere registro de lote')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la materia prima está activa')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'db_table': 'materias_primas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(help_text='Código identificador del producto. Ejemplo: 410', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del producto. Ejemplo: alfajor manjar bitter', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está en producción')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=datetime.date.today, help_text='Fecha de la producción')),
                ('meta_produccion', models.PositiveIntegerField(help_text='Meta de producción en unidades', validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la tarea', max_length=500, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], db_index=True, default='pendiente', help_text='Estado actual de la tarea', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la tarea')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha y hora en que se inició la producción', null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se finalizó la producción', null=True)),
                ('linea', models.ForeignKey(help_text='Línea donde se realizará la producción', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='produccion.linea')),
                ('producto', models.ForeignKey(help_text='Producto a fabricar', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='produccion.producto')),
                ('supervisor_asignador', models.ForeignKey(help_text='Supervisor que creó esta tarea', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'ordering': ['-fecha', 'turno', 'linea'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('AM', 'AM (06:15-13:35)'), ('Jornada', 'Jornada (08:00-17:30)'), ('PM', 'PM (13:25-22:05)')], help_text='Nombre del turno', max_length=20, unique=True)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el turno está activo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TareaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de asignación')),
                ('colaborador', models.ForeignKey(help_text='Colaborador asignado a la tarea', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to='produccion.colaborador')),
                ('tarea', models.ForeignKey(help_text='Tarea asignada', on_delete=django.db.models.deletion.CASCADE, related_name='tarea_colaboradores', to='produccion.tarea')),
            ],
            options={
                'verbose_name': 'Asignación de Colaborador',
                'verbose_name_plural': 'Asignaciones de Colaboradores',
                'db_table': 'tareas_colaboradores',
                'ordering': ['tarea', 'colaborador__codigo'],
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='turno',
            field=models.ForeignKey(help_text='Turno en que se realizará la producción', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='produccion.turno'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en la lista')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta materia prima está activa en la receta')),
                ('materia_prima', models.ForeignKey(help_text='Materia prima necesaria', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='produccion.materiaprima')),
                ('producto', models.ForeignKey(help_text='Producto al que pertenece esta materia prima', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
                'ordering': ['producto', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['codigo'], name='colaborador_codigo_576cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['nombre', 'apellido'], name='colaborador_nombre_f9e921_idx'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='tareacolaborador',
            unique_together={('tarea', 'colaborador')},
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha', 'turno', 'linea'], name='tareas_fecha_bc5fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado'], name='tareas_estado_d4b02b_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha'], name='tareas_fecha_64a44e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together={('linea', 'turno', 'fecha', 'producto')},
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['producto'], name='recetas_product_c280de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receta',
            unique_together={('producto', 'materia_prima')},
        ),
    ]
