# Generated by Django 4.2.7 on 2025-11-14 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de inicio de la hoja de procesos')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización de la hoja de procesos', null=True)),
                ('finalizada', models.BooleanField(default=False, help_text='Indica si la hoja de procesos está finalizada')),
                ('tarea', models.OneToOneField(help_text='Tarea asociada a esta hoja de procesos', on_delete=django.db.models.deletion.CASCADE, related_name='hoja_procesos', to='produccion.tarea')),
            ],
            options={
                'verbose_name': 'Hoja de Procesos',
                'verbose_name_plural': 'Hojas de Procesos',
                'db_table': 'hojas_procesos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la máquina', max_length=100)),
                ('codigo', models.CharField(help_text='Código único de la máquina', max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la máquina está operativa')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'maquinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de evento', max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Código del tipo de evento', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de evento', null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo de evento está activo')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'db_table': 'tipos_eventos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.PositiveIntegerField(help_text='Cantidad producida en unidades')),
                ('estado', models.CharField(choices=[('en_revision', 'En Revisión'), ('liberado', 'Liberado'), ('retenido', 'Retenido')], default='en_revision', help_text='Estado de la trazabilidad', max_length=20)),
                ('motivo_retencion', models.TextField(blank=True, help_text="Motivo de retención (obligatorio si estado es 'retenido')", max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la trazabilidad')),
                ('hoja_procesos', models.OneToOneField(help_text='Hoja de procesos asociada', on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='produccion.hojaprocesos')),
            ],
            options={
                'verbose_name': 'Trazabilidad',
                'verbose_name_plural': 'Trazabilidades',
                'db_table': 'trazabilidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, help_text='Cantidad de reproceso en kilogramos', max_digits=10)),
                ('descripcion', models.TextField(help_text='Descripción del reproceso', max_length=500)),
                ('trazabilidad', models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='reprocesos', to='produccion.trazabilidad')),
            ],
            options={
                'verbose_name': 'Reproceso',
                'verbose_name_plural': 'Reprocesos',
                'db_table': 'reprocesos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, help_text='Cantidad de merma en kilogramos', max_digits=10)),
                ('descripcion', models.TextField(help_text='Descripción de la merma', max_length=500)),
                ('trazabilidad', models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='produccion.trazabilidad')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'db_table': 'mermas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(help_text='Hora de inicio del evento')),
                ('hora_fin', models.DateTimeField(blank=True, help_text='Hora de fin del evento', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre este evento', max_length=500, null=True)),
                ('hoja_procesos', models.ForeignKey(help_text='Hoja de procesos a la que pertenece este evento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='produccion.hojaprocesos')),
                ('tipo_evento', models.ForeignKey(help_text='Tipo de evento', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='produccion.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento de Proceso',
                'verbose_name_plural': 'Eventos de Procesos',
                'db_table': 'eventos_procesos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, help_text='Lote de la materia prima (puede ser null si no requiere lote)', max_length=100, null=True)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, help_text='Cantidad de materia prima usada', max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('unidades', 'Unidades')], default='kg', help_text='Unidad de medida de la cantidad', max_length=20)),
                ('materia_prima', models.ForeignKey(help_text='Materia prima utilizada', on_delete=django.db.models.deletion.PROTECT, related_name='trazabilidades', to='produccion.materiaprima')),
                ('trazabilidad', models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas_usadas', to='produccion.trazabilidad')),
            ],
            options={
                'verbose_name': 'Materia Prima Usada',
                'verbose_name_plural': 'Materias Primas Usadas',
                'db_table': 'trazabilidad_materias_primas',
                'ordering': ['materia_prima__codigo'],
                'unique_together': {('trazabilidad', 'materia_prima')},
            },
        ),
        migrations.CreateModel(
            name='FirmaTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('supervisor', 'Supervisor'), ('control_calidad', 'Control de Calidad')], help_text='Tipo de firma', max_length=20)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la firma')),
                ('trazabilidad', models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='produccion.trazabilidad')),
                ('usuario', models.ForeignKey(help_text='Usuario que firmó', on_delete=django.db.models.deletion.PROTECT, related_name='firmas_trazabilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma de Trazabilidad',
                'verbose_name_plural': 'Firmas de Trazabilidad',
                'db_table': 'firmas_trazabilidad',
                'ordering': ['fecha_firma'],
                'unique_together': {('trazabilidad', 'tipo_firma')},
            },
        ),
        migrations.CreateModel(
            name='EventoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(help_text='Evento de proceso', on_delete=django.db.models.deletion.CASCADE, related_name='evento_maquinas', to='produccion.eventoproceso')),
                ('maquina', models.ForeignKey(help_text='Máquina utilizada', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='produccion.maquina')),
            ],
            options={
                'verbose_name': 'Máquina en Evento',
                'verbose_name_plural': 'Máquinas en Eventos',
                'db_table': 'eventos_maquinas',
                'unique_together': {('evento', 'maquina')},
            },
        ),
    ]
