# Generated by Django 4.2.7 on 2025-12-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='linea',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'KG'), ('UN', 'UN')], default='UN', help_text='Unidad de medida del producto (generalmente UN para unidades)', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'KG'), ('UN', 'UN')], default='KG', help_text='Unidad de medida por defecto de esta materia prima', max_length=20),
        ),
        migrations.AlterField(
            model_name='merma',
            name='causas',
            field=models.CharField(choices=[('cayo_al_suelo', 'Cayó al Suelo'), ('por_hongos', 'Por Hongos'), ('caducidad', 'Caducidad'), ('grasa_maquina', 'Grasa Máquina'), ('exposicion', 'Exposición'), ('otro', 'Otro (especificar)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reproceso',
            name='causas',
            field=models.CharField(choices=[('escasez_de_banado', 'Escasez de Bañado'), ('poca_vida_util', 'Poca Vida Útil'), ('deformacion', 'Deformación'), ('peso_erroneo', 'Peso Erróneo'), ('mal_templado', 'Mal Templado'), ('otro', 'Otro (especificar)')], max_length=200, null=True),
        ),
    ]
