# Generated by Django 4.2.7 on 2025-12-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_cargar_tipos_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merma',
            name='causas',
            field=models.CharField(choices=[('cayo_al_suelo', 'Cayó al Suelo'), ('por_hongos', 'Por Hongos'), ('caducidad', 'Caducidad'), ('grasa_maquina', 'Grasa Máquina'), ('exposicion', 'Exposición'), ('otro', 'Otro (especificar)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reproceso',
            name='causas',
            field=models.CharField(choices=[('escasez_de_banado', 'Escasez de Bañado'), ('poca_vida_util', 'Poca Vida Útil'), ('deformacion', 'Deformación'), ('peso_erroneo', 'Peso Erróneo'), ('mal_templado', 'Mal Templado'), ('otro', 'Otro (especificar)')], max_length=200, null=True),
        ),
    ]
