# Generated by Django 4.2.7 on 2025-11-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_cargar_tipos_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='causas',
            field=models.CharField(choices=[('desperdicio_corte', 'Desperdicio en Corte'), ('producto_defectuoso', 'Producto Defectuoso'), ('derrame', 'Derrame o Pérdida'), ('caducidad', 'Producto Caducado'), ('error_pesaje', 'Error en Pesaje'), ('adherencia_equipo', 'Adherencia a Equipo'), ('rechazo_calidad', 'Rechazo de Calidad'), ('otro', 'Otro (especificar)')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merma',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='causas',
            field=models.CharField(choices=[('temperatura_inadecuada', 'Temperatura Inadecuada'), ('tiempo_excedido', 'Tiempo de Proceso Excedido'), ('mezcla_incorrecta', 'Mezcla Incorrecta'), ('contaminacion', 'Contaminación'), ('error_operador', 'Error del Operador'), ('falla_maquina', 'Falla de Máquina'), ('materia_prima_defectuosa', 'Materia Prima Defectuosa'), ('otro', 'Otro (especificar)')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrazabilidadColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.colaborador')),
                ('trazabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_reales', to='produccion.trazabilidad')),
            ],
        ),
    ]
