# Generated by Django 4.2.7 on 2025-12-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_merma_causas_alter_reproceso_causas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(choices=[('kG', 'Kilogramos'), ('UN', 'Unidades')], default='kG', help_text='Unidad de medida por defecto de esta materia prima', max_length=20),
        ),
    ]
