# Generated by Django 4.2.7 on 2025-11-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_merma_causas_merma_observaciones_reproceso_causas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trazabilidadcolaborador',
            options={'ordering': ['fecha_asignacion'], 'verbose_name': 'Colaborador en Trazabilidad', 'verbose_name_plural': 'Colaboradores en Trazabilidad'},
        ),
        migrations.AlterField(
            model_name='trazabilidadcolaborador',
            name='colaborador',
            field=models.ForeignKey(help_text='Colaborador que trabajó en la producción', on_delete=django.db.models.deletion.PROTECT, to='produccion.colaborador'),
        ),
        migrations.AlterField(
            model_name='trazabilidadcolaborador',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo se registró este colaborador en la trazabilidad'),
        ),
        migrations.AlterField(
            model_name='trazabilidadcolaborador',
            name='trazabilidad',
            field=models.ForeignKey(help_text='Trazabilidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_reales', to='produccion.trazabilidad'),
        ),
        migrations.AlterUniqueTogether(
            name='trazabilidadcolaborador',
            unique_together={('trazabilidad', 'colaborador')},
        ),
        migrations.AlterModelTable(
            name='trazabilidadcolaborador',
            table='trazabilidad_colaborador',
        ),
    ]
