# Generated by Django 4.2.7 on 2025-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_cambiar_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='codigo',
            field=models.IntegerField(help_text='Código identificador del colaborador', unique=True),
        ),
    ]
