# Generated by Django 4.2.7 on 2025-12-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_alter_materiaprima_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'KG'), ('UN', 'UN')], default='KG', help_text='Unidad de medida por defecto de esta materia prima', max_length=20),
        ),
    ]
