# Generated by Django 4.2.7 on 2025-12-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_alter_materiaprima_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'KG'), ('UN', 'UN')], default='UN', help_text='Unidad de medida del producto (generalmente UN para unidades)', max_length=20),
        ),
    ]
