# Generated by Django 4.2.7 on 2025-12-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together=set(),
        ),
    ]
