# Generated by Django 4.2.7 on 2025-12-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_cargar_lineas'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazabilidad',
            name='juliano',
            field=models.PositiveIntegerField(default=-28, editable=False, help_text='Día juliano del año (1-366). Se calcula automáticamente desde fecha_creacion', verbose_name='Día Juliano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='lote',
            field=models.CharField(default=1, help_text='Lote de producción en formato: CÓDIGO_PRODUCTO-JULIANO-CÓDIGO_COLABORADOR. Ejemplo: 410-342-96', max_length=50, verbose_name='Lote'),
            preserve_default=False,
        ),
    ]
