# Generated by Django 4.2.7 on 2025-12-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_trazabilidad_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='lote',
            field=models.CharField(help_text='Lote de producción en formato: CÓDIGO_PRODUCTO-JULIANO-CÓDIGO_COLABORADOR. Ejemplo: 410-342-96', max_length=50, verbose_name='Lote'),
        ),
    ]
